### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by amonks** [radblock/plans#6]
besides a website, what does documentation mean?

it'd be cool to have a video, which could mean a lot of things.

how do we get attention?

**Comment by effincleveland** [comment]
video is in other thread. 
i think good documentation has a message embeded in it. like an advertisement almost. something to make documentation more engaging.
there should be some sort of like, interesting narrative element, something interesting that aligns with the functionality of the plugin; and potentially plays off the context of new media artist, or private art school, or both?

**Comment by amonks** [comment]
yeah totally, maybe two narratives (artist, viewer). parallel action?

shots:
- artist slavin away at photoshop _something to indicate the artist wants an audience???_
- artist uploads gif 
- viewer frowning at online ad
- viewer installs plugin
- viewer sees gif, posts it to facebook _or something_
- artist sees gif posted by someone else on facebook _is happy_

**Comment by amonks** [comment]
maybe that should have gone in the video thread

**Comment by amonks** [comment]
I'm consolidating these threads, this is silly
